name: Build and Promote Hugo

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        hugo-version:
          - 'latest'
          - '0.158.0'
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: ${{ matrix.hugo-version }}
          extended: true

      - name: Run Hugo
        run: hugo --minify

  promote:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref_name == 'main'
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Push current commit to prod
        run: git push origin HEAD:prod
